// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var S$ReScriptStruct = require("rescript-struct/src/S.bs.js");

var struct = S$ReScriptStruct.union([
      S$ReScriptStruct.object(function (o) {
            S$ReScriptStruct.discriminant(o, "type", S$ReScriptStruct.literal({
                      TAG: /* String */0,
                      _0: "typescript"
                    }));
            return {
                    TAG: /* TypeScript */0,
                    label: S$ReScriptStruct.field(o, "label", S$ReScriptStruct.string(undefined))
                  };
          }),
      S$ReScriptStruct.object(function (o) {
            S$ReScriptStruct.discriminant(o, "type", S$ReScriptStruct.literal({
                      TAG: /* String */0,
                      _0: "npm"
                    }));
            return {
                    TAG: /* NPM */1,
                    label: S$ReScriptStruct.field(o, "label", S$ReScriptStruct.string(undefined))
                  };
          }),
      S$ReScriptStruct.object(function (o) {
            S$ReScriptStruct.discriminant(o, "type", S$ReScriptStruct.literal({
                      TAG: /* String */0,
                      _0: "shell"
                    }));
            return {
                    TAG: /* Shell */2,
                    label: S$ReScriptStruct.field(o, "label", S$ReScriptStruct.string(undefined))
                  };
          }),
      S$ReScriptStruct.object(function (o) {
            S$ReScriptStruct.discriminant(o, "type", S$ReScriptStruct.literal({
                      TAG: /* String */0,
                      _0: "process"
                    }));
            return {
                    TAG: /* Process */3,
                    label: S$ReScriptStruct.field(o, "label", S$ReScriptStruct.string(undefined))
                  };
          })
    ]);

console.log(S$ReScriptStruct.serializeOrRaiseWith({
          TAG: /* TypeScript */0,
          label: "test"
        }, struct));

exports.struct = struct;
/* struct Not a pure module */
